PACKAGE_NAME="mt7902e"
PACKAGE_VERSION="git"
MAKE[0]="make KVER=$kernelver"
BUILT_MODULE_NAME[0]=$PACKAGE_NAME
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/wireless/mediatek/$PACKAGE_NAME"
AUTOINSTALL="yes"
